export * from './main.page';
export * from './register.page';
export * from './login.page';
export * from './yourfeed.page';
export * from './createArticle.page';
export * from './profile.page';
export * from './article.page';
export * from './editArticle.page';
export * from './settings.page';